// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDR50Xdwr6a3OGwiJKJs1Do4CN2EPT8y_k',
    appId: '1:1088245830395:web:b40511b4e3659a33e3965e',
    messagingSenderId: '1088245830395',
    projectId: 'el-shela-a3b1b',
    authDomain: 'el-shela-a3b1b.firebaseapp.com',
    storageBucket: 'el-shela-a3b1b.appspot.com',
    measurementId: 'G-12WX07X3VB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5PnAzml1E92boKhoq9lvVUXc-WCUFIKs',
    appId: '1:1088245830395:android:725c7994ec92d5b8e3965e',
    messagingSenderId: '1088245830395',
    projectId: 'el-shela-a3b1b',
    storageBucket: 'el-shela-a3b1b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCENkAHFWhpZEMnofXwbi89TQAKFE6bhVA',
    appId: '1:1088245830395:ios:2b4613fb539150afe3965e',
    messagingSenderId: '1088245830395',
    projectId: 'el-shela-a3b1b',
    storageBucket: 'el-shela-a3b1b.appspot.com',
    iosBundleId: 'com.example.elShela',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCENkAHFWhpZEMnofXwbi89TQAKFE6bhVA',
    appId: '1:1088245830395:ios:5b0221b4caf2a443e3965e',
    messagingSenderId: '1088245830395',
    projectId: 'el-shela-a3b1b',
    storageBucket: 'el-shela-a3b1b.appspot.com',
    iosBundleId: 'com.example.elShela.RunnerTests',
  );
}
